-- Supabase schema for Aivana e-commerce platform

-- Enable UUID extension if needed
-- create extension if not exists "uuid-ossp";

-- Users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text unique not null,
  password_hash text not null,
  role text default 'seller',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable the pgvector extension
create extension if not exists vector;

-- Products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  currency text default 'USD',
  stock_quantity integer default 0,
  category_id bigint references categories(id),
  image_url text,
  description_embedding vector(1536), -- Vector column for storing embeddings (OpenAI's text-embedding-ada-002 returns 1536-dimensional vectors)
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transactions table
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references users(id),
  product_id bigint not null references products(id),
  quantity integer not null,
  total_price numeric not null,
  currency text default 'USD',
  eth_transaction_hash text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Conversations table (for AI agent interactions)
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  session_id text not null,
  message text not null,
  sender_type text not null, -- 'user' or 'ai'
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) policies - adjust as needed
alter table users enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table transactions enable row level security;
alter table conversations enable row level security;

-- Indexes for better performance
create index if not exists idx_products_category_id on products(category_id);
create index if not exists idx_transactions_buyer_id on transactions(buyer_id);
create index if not exists idx_transactions_product_id on transactions(product_id);
create index if not exists idx_conversations_session_id on conversations(session_id);
create index if not exists idx_conversations_timestamp on conversations(timestamp);

-- Function to update the 'updated_at' column
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Function for semantic search using vector similarity
create or replace function get_similar_products(query_embedding vector(1536), limit_count int default 5)
returns setof products
language sql
as $$
  select *
  from products
  where status != 'archived'
  order by description_embedding <=> query_embedding
  limit limit_count;
$$;

-- Triggers to update 'updated_at' column
create trigger update_users_updated_at before update on users
  for each row execute procedure update_updated_at_column();

create trigger update_categories_updated_at before update on categories
  for each row execute procedure update_updated_at_column();

create trigger update_products_updated_at before update on products
  for each row execute procedure update_updated_at_column();