-- Supabase schema for Aivana e-commerce platform

-- Enable UUID extension if needed
-- create extension if not exists "uuid-ossp";

-- Users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text unique not null,
  password_hash text not null,
  role text default 'seller',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable the pgvector extension
create extension if not exists vector;

-- Products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  currency text default 'USDC',
  stock_quantity integer default 0,
  category_id bigint references categories(id),
  image_url text,
  description_embedding vector(1536), -- Vector column for storing embeddings (OpenAI's text-embedding-ada-002 returns 1536-dimensional vectors)
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Shopping cart sessions table (general cart information)
create table if not exists cart_sessions (
  id bigint generated by default as identity primary key,
  session_id text unique not null, -- Session identifier
  buyer_name text, -- Optional buyer name
  shipping_address text, -- Optional shipping address
  notes text, -- Optional notes about the cart/session
  status text default 'pending', -- Status of the cart: 'pending' or 'paid'
  transaction_id text, -- Transaction ID from blockchain (optional, added when payment confirmed)
  buyer_wallet_id text, -- Buyer's wallet ID (optional, added when payment confirmed)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Shopping cart items table (specific products in each cart)
create table if not exists cart_items (
  id bigint generated by default as identity primary key,
  cart_session_id bigint not null references cart_sessions(id) on delete cascade,
  product_id bigint not null references products(id),
  quantity integer not null default 1,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(cart_session_id, product_id) -- Prevent duplicate products in the same cart
);

-- Conversations table (for AI agent interactions)
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  session_id text not null,
  message text not null,
  sender_type text not null, -- 'user' or 'ai'
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) policies - adjust as needed
-- alter table users enable row level security;
-- alter table categories enable row level security;
-- alter table products enable row level security;
-- alter table transactions enable row level security;
-- alter table conversations enable row level security;
-- alter table shopping_cart enable row level security;

-- Indexes for better performance
create index if not exists idx_products_category_id on products(category_id);
create index if not exists idx_conversations_user_id on conversations(user_id);
create index if not exists idx_conversations_session_id on conversations(session_id);
create index if not exists idx_conversations_timestamp on conversations(timestamp);
create index if not exists idx_cart_sessions_session_id on cart_sessions(session_id);
create index if not exists idx_cart_sessions_status on cart_sessions(status);
create index if not exists idx_cart_sessions_transaction_id on cart_sessions(transaction_id);
create index if not exists idx_cart_items_cart_session_id on cart_items(cart_session_id);
create index if not exists idx_cart_items_product_id on cart_items(product_id);

-- Function to update the 'updated_at' column
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Function for semantic search using vector similarity
create or replace function get_similar_products(query_embedding vector(1536), limit_count int default 5)
returns table (id bigint, name text, description text, price numeric, currency text, stock_quantity int, category_id bigint, image_url text, created_at timestamptz, updated_at timestamptz, status text )
language sql
as $$
  select id, name, description, price, currency, stock_quantity, category_id, image_url, created_at, updated_at, status
  from products
  where status != 'archived'
  order by description_embedding <=> query_embedding
  limit limit_count;
$$;

-- Triggers to update 'updated_at' column
create trigger update_users_updated_at before update on users
  for each row execute procedure update_updated_at_column();

create trigger update_categories_updated_at before update on categories
  for each row execute procedure update_updated_at_column();

create trigger update_products_updated_at before update on products
  for each row execute procedure update_updated_at_column();

create trigger update_cart_sessions_updated_at before update on cart_sessions
  for each row execute procedure update_updated_at_column();

create trigger update_cart_items_updated_at before update on cart_items
  for each row execute procedure update_updated_at_column();